services:
 nodejs:
   build:
    context: .
   image: imagem_exemplo
   depends_on:
    - mysql
   volumes:
    - .:/home/node/app
   ports:
    - "5000:5000"
   environment:
    - MYSQL_PASS:123
   container_name: app
 mysql:
   image: mysql:latest
   ports:
    - "3306:3306"
   environment:
    - MYSQL_ROOT_PASSWORD=123
   container_name: mysql

 phpmyadmin:
   image: phpmyadmin:latest
   depends_on:
    - mysql
   ports:
    - "8081:80"
   volumes:
    - /sessions
   environment:
    - PMA_HOST=mysql
    - PMA_PORT=3306
   container_name: phpmyadmin